name: 'Swift Android Action'
description: 'Cross-compiles a swift package for Android and runs the test cases in an Android emulator'
branding:
  icon: 'target'
  color: 'orange'
inputs:
  swift-version:
    description: 'The version of the Swift toolchain to use'
    required: true
    default: '6.0.2'
  package-path:
    description: 'The folder where the swift package is checked out'
    required: true
    default: '.'
  swift-build-flags:
    description: 'Additional flags to pass to the swift build command'
    required: true
    default: ''
  swift-test-flags:
    description: 'Additional flags to pass to the swift test command'
    required: true
    default: ''
  android-emulator-options:
    description: 'Options to pass to the Android emulator'
    required: true
    default: '-no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim'
  android-emulator-boot-timeout:
    description: 'Emulator boot timeout in seconds'
    required: true
    default: 600
  run-tests:
    description: 'Whether to run the tests or just the build'
    required: true
    default: 'true'
  android-api-level:
    description: 'The API level of the Android emulator to run against'
    required: true
    default: 29
runs:
  using: "composite"
  steps:
    - name: Setup swift-android-action
      id: setup
      shell: bash
      run: |
        if [ ${RUNNER_OS} == 'Linux' ]; then
          # fetch OS variables like ID ("ubuntu") and VERSION_ID ("24.04")
          . /etc/os-release
          echo "osidpair=${ID}${VERSION_ID}" >> $GITHUB_OUTPUT
          echo "osid=${ID}$(echo ${VERSION_ID} | tr -d '.')" >> $GITHUB_OUTPUT
        elif [ ${RUNNER_OS} == 'macOS' ]; then
          echo "osidpair=macos" >> $GITHUB_OUTPUT
          echo "osid=macos" >> $GITHUB_OUTPUT
        else
          echo "Unsupported platform: ${RUNNER_OS}"
          exit 1
        fi

        # RUNNER_ARCH	The architecture of the runner executing the job. Possible values are X86, X64, ARM, or ARM64.
        if [ ${RUNNER_ARCH} == 'X64' ]; then
          echo "android-sdk-arch=x86_64" >> $GITHUB_OUTPUT
          echo "android-emulator-arch=x86_64" >> $GITHUB_OUTPUT
        elif [ ${RUNNER_ARCH} == 'ARM64' ]; then
          echo "android-sdk-arch=aarch64" >> $GITHUB_OUTPUT
          echo "android-emulator-arch=arm64-v8a" >> $GITHUB_OUTPUT
        else
          echo "Unsupported architecture: ${RUNNER_ARCH}"
          exit 1
        fi

    - name: Cache Swift Host Toolchain
      uses: actions/cache@v4
      id: cache-swift
      with:
        path: ~/swift-download
        key: "swift-${{ inputs.swift-version }}-${{ steps.setup.outputs.osid }}"
    - name: Download Swift Host Toolchain
      if: steps.cache-swift.outputs.cache-hit != 'true'
      shell: bash
      run: |
        SWIFT_ID="swift-${{ inputs.swift-version }}-RELEASE"
        mkdir -p ~/swift-download
        cd ~/swift-download
        if [ ${RUNNER_OS} == 'Linux' ]; then
          curl -fsSL https://download.swift.org/swift-${{ inputs.swift-version }}-release/${{ steps.setup.outputs.osid }}/${SWIFT_ID}/${SWIFT_ID}-${{ steps.setup.outputs.osidpair }}.tar.gz --output swift.tar.gz
        elif [ ${RUNNER_OS} == 'macOS' ]; then
          curl -fsSL https://download.swift.org/swift-${{ inputs.swift-version }}-release/xcode/${SWIFT_ID}/${SWIFT_ID}-osx.pkg --output swift.pkg
        else
          echo "Unsupported platform: ${RUNNER_OS}"
          exit 1
        fi
    - name: Install Swift Host Toolchain
      shell: bash
      run: |
        cd ~/swift-download
        SWIFT_ID="swift-${{ inputs.swift-version }}-RELEASE"
        if [ ${RUNNER_OS} == 'Linux' ]; then
          mkdir -p ${HOME}/swift/$SWIFT_ID
          tar -xzf swift.tar.gz -C ~/swift/$SWIFT_ID --strip 1
          SWIFT_INSTALLATION=$HOME/swift/$SWIFT_ID/usr
        elif [ ${RUNNER_OS} == 'macOS' ]; then
          /usr/sbin/installer -pkg swift.pkg -target CurrentUserHomeDirectory
          SWIFT_INSTALLATION=${HOME}/Library/Developer/Toolchains/${SWIFT_ID}.xctoolchain/usr
          echo "TOOLCHAINS=$(plutil -extract CFBundleIdentifier raw ${SWIFT_INSTALLATION}/Info.plist)" >> $GITHUB_ENV
        else
          echo "Unsupported platform: ${RUNNER_OS}"
          exit 1
        fi
        echo "SWIFT_INSTALLATION=${SWIFT_INSTALLATION}" >> $GITHUB_ENV
        echo "${SWIFT_INSTALLATION}/bin" >> $GITHUB_PATH
    - name: Check Swift Version
      shell: bash
      run: |
        swift --version
    - name: Install Swift Android SDK
      shell: bash
      run: |
        set +x
        SWIFT_SDK_ID="swift-${{ inputs.swift-version }}-RELEASE-android-24-0.1"
        echo "SWIFT_SDK_TARGET=${SWIFT_SDK_TARGET}" >> $GITHUB_ENV

        # variant that identifies the SDK
        SWIFT_SDK_ID_SHORT="swift-${{ inputs.swift-version }}-release-android-24-sdk"
        echo "SWIFT_SDK_ID_SHORT=${SWIFT_SDK_ID_SHORT}" >> $GITHUB_ENV

        SWIFT_SDK_TARGET="${{ steps.setup.outputs.android-sdk-arch }}-unknown-linux-android24"
        echo "SWIFT_SDK_TARGET=${SWIFT_SDK_TARGET}" >> $GITHUB_ENV

        mkdir -p ${RUNNER_TEMP}/swift-android-toolchain
        cd ${RUNNER_TEMP}/swift-android-toolchain
        curl -fsSL https://github.com/skiptools/swift-android-toolchain/releases/download/${{ inputs.swift-version }}/${SWIFT_SDK_ID}.artifactbundle.tar.gz --output ${SWIFT_SDK_ID}.artifactbundle.tar.gz
        swift sdk install ${SWIFT_SDK_ID}.artifactbundle.tar.gz

        swift sdk configure --show-configuration ${SWIFT_SDK_ID} ${SWIFT_SDK_TARGET}

        if [ ${RUNNER_OS} == 'Linux' ]; then
          SWIFT_SDK_ROOT="${HOME}/.config/swiftpm/swift-sdks"
        elif [ ${RUNNER_OS} == 'macOS' ]; then
          SWIFT_SDK_ROOT="${HOME}/.swiftpm/swift-sdks"
        else
          echo "Unsupported platform for SDK: ${RUNNER_OS}"
          exit 1
        fi

        SWIFT_SDK_HOME="${SWIFT_SDK_ROOT}/${SWIFT_SDK_ID}.artifactbundle"
        echo "SWIFT_SDK_HOME 1: ${SWIFT_SDK_HOME}"

        # extract the artifact ID from the info.plist in the SDK root
        SWIFT_SDK_ARTIFACT_ID=$(cat ${SWIFT_SDK_HOME}/info.json | jq -r '.artifacts | keys[0]')
        SWIFT_SDK_HOME="${SWIFT_SDK_HOME}/${SWIFT_SDK_ARTIFACT_ID}"
        echo "SWIFT_SDK_ARTIFACT_ID: ${SWIFT_SDK_ARTIFACT_ID}"
        echo "SWIFT_SDK_HOME 2: ${SWIFT_SDK_HOME}"

        # extract the sdkRootPath from the swift-sdk.json
        SWIFT_SDK_ROOT_PATH=$(cat ${SWIFT_SDK_HOME}/swift-sdk.json | jq -r '.targetTriples.[].sdkRootPath' | head -n 1)
        SWIFT_SDK_HOME="${SWIFT_SDK_HOME}/${SWIFT_SDK_ROOT_PATH}"
        echo "SWIFT_SDK_HOME 3: ${SWIFT_SDK_HOME}"

        echo "SWIFT_SDK_HOME=${SWIFT_SDK_HOME}" >> $GITHUB_ENV
    - name: Build Swift Package with Android SDK
      shell: bash
      run: |
        SKIP_BRIDGE=1 swift build --build-tests --swift-sdk ${SWIFT_SDK_TARGET} -Xswiftc -Xclang-linker -Xswiftc -fuse-ld=lld -Xswiftc -DSKIP_BRIDGE
    - name: Prepare Android Emulator Test Script
      if: ${{ inputs.run-tests == 'true' }}
      shell: bash
      run: |
        set -x

        mkdir android-xctest
        cp -v .build/${SWIFT_SDK_TARGET}/debug/*.xctest android-xctest

        # 6.0.2 keeps libraries in per-API folders
        cp -vf ${SWIFT_SDK_HOME}/usr/lib/${{ steps.setup.outputs.android-sdk-arch }}-linux-android/*/lib*.so android-xctest || true

        # 6.0.3 keeps libraries in the parent folder
        cp -vf ${SWIFT_SDK_HOME}/usr/lib/${{ steps.setup.outputs.android-sdk-arch }}-linux-android/lib*.so android-xctest || true

        rm -v android-xctest/lib{c,dl,log,m,z}.so

        echo "adb push android-xctest /data/local/tmp" > ~/test-toolchain.sh
        for XCTEST in android-xctest/*.xctest; do
          echo "adb shell /data/local/tmp/${XCTEST}" >> ~/test-toolchain.sh
        done

        chmod +x ~/test-toolchain.sh
    - name: Run Tests on Android emulator
      if: ${{ inputs.run-tests == 'true' }}
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ inputs.android-api-level }}
        emulator-boot-timeout: ${{ inputs.android-emulator-boot-timeout }}
        emulator-options: ${{ inputs.android-emulator-options }}
        arch: ${{ steps.setup.outputs.android-emulator-arch }}
        script: ~/test-toolchain.sh

