name: swift-android-action ci
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  demo:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-24.04', 'ubuntu-22.04', 'ubuntu-20.04', 'macos-12', 'macos-13', 'macos-14-large', 'macos-15', 'macos-15-large', 'windows-2025']
    steps:
      - uses: actions/checkout@v4
        with:
          repository: skiptools/swift-sqlite
      - uses: marcprux/swift-android-action@main

