name: swift-android-action ci
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  demo:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-24.04', 'ubuntu-22.04', 'ubuntu-20.04', 'macos-13', 'macos-15']
    steps:
      - uses: actions/checkout@v4
        with:
          repository: apple/swift-algorithms
          path: apple/swift-algorithms
      - uses: marcprux/swift-android-action@main
        with:
          package-path: apple/swift-algorithms
          run-tests: ${{ matrix.os != 'macos-15' }} # no tests on macOS ARM

      - uses: actions/checkout@v4
        with:
          repository: apple/swift-crypto
          path: apple/swift-crypto
      - uses: marcprux/swift-android-action@main
        with:
          package-path: apple/swift-crypto
          run-tests: ${{ matrix.os != 'macos-15' }} # no tests on macOS ARM

      - uses: actions/checkout@v4
        with:
          repository: apple/swift-nio
          path: apple/swift-nio
      - uses: marcprux/swift-android-action@main
        with:
          package-path: apple/swift-nio
          run-tests: ${{ matrix.os != 'macos-15' }} # no tests on macOS ARM

      - uses: actions/checkout@v4
        with:
          repository: apple/swift-system
          path: apple/swift-system
      - uses: marcprux/swift-android-action@main
        with:
          package-path: apple/swift-system
          run-tests: ${{ matrix.os != 'macos-15' }} # no tests on macOS ARM

      - uses: actions/checkout@v4
        with:
          repository: apple/swift-collections
          path: apple/swift-collections
      - uses: marcprux/swift-android-action@main
        with:
          package-path: apple/swift-collections
          run-tests: ${{ matrix.os != 'macos-15' }} # no tests on macOS ARM

      - uses: actions/checkout@v4
        with:
          repository: apple/swift-atomics
          path: apple/swift-atomics
      - uses: marcprux/swift-android-action@main
        with:
          package-path: apple/swift-atomics
          run-tests: ${{ matrix.os != 'macos-15' }} # no tests on macOS ARM

      - uses: actions/checkout@v4
        with:
          repository: skiptools/swift-sqlite
          path: skiptools/swift-sqlite
      - uses: marcprux/swift-android-action@main
        with:
          package-path: skiptools/swift-sqlite
          run-tests: ${{ matrix.os != 'macos-15' }} # no tests on macOS ARM

