name: swift-android-action ci
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  demo:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-24.04', 'ubuntu-22.04', 'macos-13', 'macos-15']
    steps:
      - uses: actions/checkout@v4
        with:
          repository: skiptools/swift-sqlite
      - uses: marcprux/swift-android-action@main

